### ISSUE TITLE
Add ability to customize testsuite.name

### ISSUE THREAD

**Issue by tbpg** [sj26/rspec_junit_formatter#87]
It would be great to be able to fully customize `testsuite.name`. The test parser I'm using makes it very prominent, so I'd like the ability to set it to something more descriptive.

**Proposed solution:**

Update `name` to check for a `RSPEC_TESTSUITE_NAME` environment variable and default to the current value:
https://github.com/sj26/rspec_junit_formatter/blob/3738c28ed77877a14edf1fda429243e188797a64/lib/rspec_junit_formatter.rb#L19

`TEST_ENV_NUMBER` could either be ignored in `name`, or it could be appended to `RSPEC_TESTSUITE_NAME`. I'm good either way.

**Comment by tbpg** [comment]
Thinking about it more, I'd prefer if `TEST_ENV_NUMBER` was ignored so tests get consistent descriptions.

I'd be happy to send a PR if you're open to it.

**Comment by sj26** [comment]
Hi @tbpg! This is a nice suggestion, but I'm hesitant to add too many knobs and dials to this formatter given rspec doesn't really provide an official way to configure such formatters. Otherwise we'll start heading toward environment variable soup. The `$TEST_ENV_NUMBER` was a special case which snuck in early because it was supplied in many environments already, and was not invented for the formatter.

I'd prefer if you were able to post-process the output to prepare it for presentation in your particular tool or interface, something like:

```ruby
# script/post-process-junit
#!/usr/bin/env ruby
require "nokogiri"
document = Nokogiri::XML.parse(File.read("tmp/rspec.xml"))
document.at_xpath("testsuite")["name"] = "My Lovely Test Suite"
File.write("tmp/rspec.xml", document.to_xml)
```

Would that work?

**Comment by tbpg** [comment]
That definitely makes sense. Thank you for the workaround script! We can make that work.
